# Generated by Django 4.0.1 on 2022-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='name_region',
            field=models.TextField(max_length=50),
        ),
    ]
