# Generated by Django 4.0.1 on 2022-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_regions_name_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='name_region',
            field=models.CharField(max_length=50),
        ),
    ]
